### ISSUE TITLE
Display meta data for databse

### ISSUE THREAD

**Issue by malte-b** [hpi-bp1819-naumann/backend#5]
- [X] all table names

- [X] all (distinct) column names

- [x] all schema names 

- [x] some example entries for a given table/column (HEAD)

Get information about specific table:

```javascript
{
  ["tables": [
    "name": "",
    "columns": [
      "name": "",
      "datatype": ""
    ]
  ]
 ]
}
```

- [x] all column names in specific table name

- [x] datatype in a specific column

Meta data:

- [x] get jdbc driver name + version

- [x] get database product name + version

**Comment by mschroederi** [comment]
- Why _distinct_ column names? Aren't the column names always distinct?
- And what do you mean with _schema names_? Isn't a table a schema too?

**Comment by malte-b** [comment]
> * Why _distinct_ column names? Aren't the column names always distinct?

> * And what do you mean with _schema names_? Isn't a table a schema too?
`ResultSet getSchemas() throws SQLException;

- Distinct in the sense that many tables may have the same column names, but we only want to output them once.

- `

      Retrieves the schema names available in this database.  The results
      are ordered by <code>TABLE_CATALOG</code> and
      <code>TABLE_SCHEM</code>.
     
      <P>The schema columns are:
       <OL>
       <LI><B>TABLE_SCHEM</B> String {@code =>} schema name
       <LI><B>TABLE_CATALOG</B> String {@code =>} catalog name (may be <code>null</code>)
       </OL>`
